spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:dummy-mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:api}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:api_user}
    password: ${MYSQL_PASSWORD:dummy}
